name: 'Conventional Commits Check'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate Conventional Commits
      uses: webiny/action-conventional-commits@v1.3.0
