- name: Remove Namespaces dir before generation
  ansible.builtin.file:
    path: "{{ _current_env_dir }}/Namespaces"
    state: absent

- name: Recreate Namespaces dir
  ansible.builtin.file:
    path: "{{ _current_env_dir }}/Namespaces"
    state: directory
