---
- name: Generate jobs set
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
#    - name: Process external definitions
#      block:
#        - name: Get and unpack external definitions
#          ansible.builtin.unarchive:
#            src: "{{ jenkins_artifacts_dir }}/{{ app_reg_defs_job }}/definitions.zip"
#            dest: "/tmp/external_defs"
#            remote_src: true
#
#        - name: Copy external AppDefs to environment
#          ansible.builtin.copy:
#            src: "/tmp/external_defs/{{ app_defs_path }}/"
#            dest: "{{ current_env_dir }}/AppDefs/"
#            remote_src: true
#          when: app_defs_path is defined
#
#        - name: Copy external RegDefs to environment
#          ansible.builtin.copy:
#            src: "/tmp/external_defs/{{ reg_defs_path }}/"
#            dest: "{{ current_env_dir }}/RegDefs/"
#            remote_src: true
#          when: reg_defs_path is defined
#      when: use_external_defs

