---
- name: Prepare script arguments
  set_fact:
    script_args: "-e {{ environment_name }} -c {{ cluster_name }} -o {{ base_dir }}/environments -t {{ build_env_path }}/templates -i {{ base_dir }}/environments -k {{ atrifact_latest_version | default(version)}}"

- name: Log script args
  debug:
    msg: "{{ script_args }}"

- name: Run script
  shell: "cd {{ build_env_path }}; python3 {{ build_env_path }}/scripts/build_env/main.py {{script_args}}"
