# Requires setting an encryption key: `SECRET_KEY` or `ENVGENE_AGE_PRIVATE_KEY`, `PUBLIC_AGE_KEYS`
crypt: True
# Optional. Default value - `Fernet`
# Defines the encryption technology
# Requires setting an encryption key: `SECRET_KEY` or `ENVGENE_AGE_PRIVATE_KEY`, `PUBLIC_AGE_KEYS`
crypt_backend: SOPS
# Optional. Default value - `true`
# Specifies if Shade Credential Files generation is enabled
crypt_create_shades: True 