version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "andyroode"
    assignees:
      - "andyroode"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "dependabot"
    ignore:
      # Ignore updates for specific actions if needed
      # - dependency-name: "actions/checkout"
      #   update-types: ["version-update:semver-major"]
