- version: "app1:1.0"
  deployPostfix: "core"
  namespace: "core"
  wave: 0
  generationType: "UniqForApp"
  generationId: ""
- version: "crm:1.0"
  deployPostfix: "bss"
  namespace: "bss-origin"
  wave: 0
  generationType: "UniqForApp"
  generationId: ""
- version: "crm:1.0"
  deployPostfix: "bss"
  namespace: "bss-peer"
  wave: 0
  generationType: "UniqForApp"
  generationId: ""
