- version: "Test-App-Name:0.0.1-Test"
  deployPostfix: "app"
  namespace: "test-environment-app"
  wave: 0
  generationType: "UniqForApp"
  generationId: ""
- version: "Test-App-DB-Name:0.0.1-Test"
  deployPostfix: "app-core"
  namespace: "app-core"
  wave: 0
  generationType: "UniqForApp"
  generationId: ""
- version: "Test-App-Name:0.0.2-Test"
  deployPostfix: "app"
  namespace: "test-environment-app"
  wave: 0
  generationType: "UniqForApp"
  generationId: ""
