service-integration-cred:
  type: usernamePassword
  data:
    username: service-integration-username
    password: service-integration-password
external-integration-cred:
  type: usernamePassword
  data:
    username: external-integration-username
    password: external-integration-password
