# This action is hidden from the GitHub Actions UI
name: 'Build Effective Set Generator Docker Image'
description: 'Build and push Effective Set Generator docker image to container registry'

inputs:
  registry:
    description: 'Container registry URL'
    required: false
    default: 'ghcr.io'
  repository-owner:
    description: 'Repository owner for Docker images'
    required: false
    default: 'netcracker'
  image-name:
    description: 'Docker image name'
    required: false
    default: 'qubership-effective-set-generator'
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: './build_effective_set_generator_java/Dockerfile'
  git-user:
    description: 'Git username for build args'
    required: false
  git-token:
    description: 'Git token for build args'
    required: false
  github-token:
    description: 'GitHub token for registry login'
    required: true

outputs:
  custom_tag:
    description: 'Custom tag with timestamp'
    value: ${{ steps.tags.outputs.custom_tag }}
  branch_tag:
    description: 'Branch-based tag'
    value: ${{ steps.tags.outputs.branch_tag }}
  timestamp:
    description: 'Generated timestamp'
    value: ${{ steps.tags.outputs.timestamp }}
  branch_latest_tag:
    description: 'Branch latest tag'
    value: ${{ steps.tags.outputs.branch_latest_tag }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: effective_set_jar
        path: downloaded_artifact

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Generate Docker tags
      id: tags
      uses: ./.github/actions/generate-docker-tags

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.repository-owner }}/${{ inputs.image-name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-{{sha}},suffix={{date 'YYYYMMDD-HHMMSS'}}
          type=raw,value={{branch}}_{{date 'YYYYMMDD-HHMMSS'}}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: |
          ${{ inputs.registry }}/${{ inputs.repository-owner }}/${{ inputs.image-name }}:${{ steps.tags.outputs.custom_tag }}
          ${{ inputs.registry }}/${{ inputs.repository-owner }}/${{ inputs.image-name }}:${{ steps.tags.outputs.branch_latest_tag }}
          ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          GIT_USER=${{ inputs.git-user }}
          GIT_TOKEN=${{ inputs.git-token }}
