"""Registry of cred-ids known to originate from Cloud Passport.

Source: cred-id keys aggregated from every `*-creds.yml` file under
`environments/*/cloud-passport/` across 25 real EnvGene instance repositories
(`/home/evpo0221/Downloads/projects/instance-repos`, snapshot 2026-08-06).

Purpose: signal source for classifier - when a cred-id in a template plan matches
this registry, plan_cmd flips defaults to passport-tier shape and attaches a
suggestion recommending the operator remove the entry (value comes from Cloud
Passport in the Instance repo).

False positives are handled by plan review (T2 / I3): the operator sees the
suggestion and either accepts the passport-tier defaults, edits them, or removes
the entry entirely.

104 unique cred-ids. Frequency ranges from 1/25 (long tail, per-project) to
18/25 (`coreexternal`, most common).
"""

KNOWN_CLOUD_PASSPORT_CRED_IDS = frozenset({
    "ADMIN_TOKEN_CONSUL_CMDB_TELUS",
    "FTP_CREDENTIALS",
    "ID_CDN_STORAGE_CREDS",
    "ID_DBAAS_DBAAS_CLUSTER_DBA_CREDENTIALS",
    "ID_IDP_ADMIN_USER",
    "ID_MAAS_CREDS",
    "ID_STORAGE_PROXY_CREDS",
    "akhq-creds",
    "app-deployer-cred",
    "app-deployer-creds",
    "app-deployer-eks-token",
    "app-deployer-sa-token",
    "app-deployer-token",
    "app-deployer-token-cred",
    "app-deployer-username-cred",
    "appdeployer-creds",
    "appdeployer-token",
    "arango-backup-db-creds",
    "arango-db-creds",
    "argocd-cred",
    "argocd-creds",
    "argocd-gitlab-cred",
    "cdc-streaming-cred",
    "cdc-streaming-platform-creds",
    "cdt-creds",
    "cip-hadoop-principal",
    "cip-hadoop-truststore-password",
    "cip-slp-client-cred",
    "clickhouse-db-creds",
    "cloud-deploy-sa-token",
    "cloud-deployer-auth",
    "cloud-deployer-sa-token",
    "cmdb",
    "cmdb-user",
    "common-minio-cred",
    "consul",
    "consul-admin-cred",
    "consul-bootstrap-token",
    "consul-token",
    "coreexternal",
    "cow-auth-1-creds",
    "cpq-admin-default-cred",
    "cse-graylog-cred",
    "dbaas",
    "dbaas-cluster-dba-cred",
    "dbaas-cluster-dba-creds",
    "dbaas-discr-tool-user-creds",
    "dcl-git-creds",
    "grafana-creds",
    "graylog",
    "k8s-token",
    "kafka-admin-creds",
    "kafka-client-creds",
    "kafka-cred",
    "kafka-monitoring-creds",
    "keycloak-client-cred",
    "logging-creds",
    "maas-account-manager-cred",
    "maas-admin-creds",
    "maas-client-creds",
    "maas-cred",
    "maas_account_manager",
    "maasexternal",
    "migration-tools-nifi-secret",
    "minio-storage-cred",
    "mongo-backup-db-creds",
    "mongo-backup-monitoring-creds",
    "mongo-db-creds",
    "mongo-monitoring-creds",
    "monitoringexternal",
    "nc-apps-deployer",
    "ndo-cloud-core-admin-creds",
    "ndo-default-tenant-creds",
    "ndo-idp-admin-creds",
    "ndo-mistral-pg-creds",
    "ndo-superset-creds",
    "nexus-creds",
    "nifi-sensitive-key-cred",
    "nrm-kafka-cred",
    "nrm-postgresql-cred",
    "opensearch-creds",
    "openstack-tenant-creds",
    "oss-streaming-cred",
    "oss-streaming-platform-creds",
    "postgresql-db-creds",
    "postgresql-migration-db-creds",
    "postgresql-reporting-db-creds",
    "rabbitmq-creds",
    "registry-cred",
    "registry-creds",
    "s3-storage-creds",
    "smtp-cred",
    "sops",
    "ssm-cmdb-cred",
    "sso-idp-admin-login",
    "sso-idp-admin-password",
    "storage",
    "storage-proxy",
    "streaming",
    "streamingPlatform-cred",
    "tenant-admin-login",
    "vmauth-creds",
    "zookeeper-admin-creds",
    "zookeeper-client-creds",
})
