from os import path

from .__main__ import handle_exception
from .yaml_helper import copy, json, pathlib, threading, StringIO, OrderedDict, jschon, jschon_tools, jsonschema, ruyaml, RefResolver, CommentedMap, CommentedSeq, DoubleQuotedScalarString, LiteralScalarString, pyyaml, openJson
from .file_helper import os, glob, re, shutil, tarfile, time, zipfile, Callable, Path, is_dir_empty
from .yaml_helper import convert_dict_to_yaml, dumpYamlToStr, addHeaderToYaml, alignYamlFileComments, deleteCommentByKey, alignYamlComments, sortYaml, get_nested_yaml_attribute_or_fail, set_nested_yaml_attribute, merge_yaml_into_target, store_value_to_yaml, merge_dict_key_with_comment, beautifyYaml, find_yaml_file, findYamls, findAllYamlsInDir, mergeYamlInDir, make_quotes_for_all_strings, make_quotes_for_strings, normalize_comments, copy_yaml_and_remove_empty_dicts, empty_yaml, yaml_from_string, find_files_by_basename, load_json_or_yaml, get_empty_yaml, openYaml, readYaml, validate_yaml_by_scheme_or_fail, validate_yaml_data_by_schema, writeYamlToFile, get_or_create_nested_yaml_attribute, create_yaml_processor, yaml, safe_yaml
from .file_helper import extractNameFromFile, extractNameWithExtensionFromFile, extractNameFromDir, check_file_exists, check_dir_exists, identify_yaml_extension, find_all_sub_dir, check_dir_exist_and_create, delete_dir, is_glob, is_source_path_valid, copy_path, move_path, openFileAsString, deleteFile, deleteFileIfExists, getAbsPath, get_parent_dir_for_dir, getDirName, getParentDirName, findAllFilesInDir, findFiles, get_all_files_in_dir, ensure_directory, unpack_archive, cleanup_dir, is_dir_empty, is_over_size_limit, cleanup_dir_by_age, delete_dir_if_exists
from .business_helper import find_env_instances_dir, getenv_and_log, getenv_with_error, getenv, get_schema_dir, get_env_instances_dir, get_current_env_dir_from_env_vars, check_environment_is_valid_or_fail, check_env_definition_is_valid_or_fail, getTemplateArtifactName, getEnvDefinition, getEnvDefinitionPath, ensure_environment_name, getEnvCredentials, getEnvCredentialsPath, getAppDefinitionPath, getTemplateVersionFromEnvDefinition, getTemplateLatestSnapshotVersion, update_generated_versions, extract_namespace_from_application_path, extract_namespace_from_namespace_path, contains_cyrillic, check_for_cyrillic, get_cluster_name_from_full_name, get_environment_name_from_full_name, find_cloud_passport_definition, find_passport_by_env_definition, findPassportInDefaultDirByName, find_cloud_name_from_passport, NamespaceRole, parse_bg_ns_target, get_namespace_role, NamespaceFile, get_namespaces_path, get_bgd_path, get_bgd_object, get_namespaces, get_template_dirs, is_from_template_dir, get_sboms_dir, pubreg_transient_dir, render_workspace_dir, get_app_artifacts_dir, get_env_dir_by_env_cluster_name, is_inventory_generation_needed, get_version, INVENTORY_DIR_NAME, ENV_DEFINITION_FILE_NAME, CREDENTIALS_DIR_NAME, CREDENTIALS_FILE_NAME, BUILD_ENV_TAG, CMDB_IMPORT_TAG, DEFAULT_PASSPORT_NAME, DEFAULT_PASSPORT_DIR_NAME, INV_GEN_CREDS_PATH, PUBREG_PARAMS_FILENAME, TEMPLATE_DIR_PATTERN
from .config_helper import get_envgene_config_yaml, get_regdef_schema, get_regdef_v2_schema, validate_regdef_or_fail, get_regdef_schema_for_content, get_artifact_size_limit_mb, get_save_artifacts_strategy, get_sbom_retention_size_limit_mb
from .json_helper import findAllJsonsInDir, writeJsonToFile
from .collections_helper import merge_lists, is_primitive, dump_as_yaml_format, get_merged_param_value, dict_merge, split_multi_value_param
from .creds_helper import check_is_cred, create_cred_definition, get_cred_list_from_param, get_cred_id_from_cred_macros, expand_cred_macro_and_return_value, get_value_from_cred, check_is_envgen_cred, get_cred_id_and_property_from_cred_macros, mask_sensitive, fetch_cred_value, extra_creds_scope, register_extra_creds, get_cred_config, validate_creds, check_cred_value, is_envgenenullvalue, validate_cred_types, copy_creds_to_env_creds_file, get_cred_data, CRED_TYPE_SECRET, CRED_TYPE_USERPASS, CRED_TYPE_VAULT, CRED_VALUE_TYPE_USERNAME, CRED_VALUE_TYPE_PASSWORD, CRED_VALUE_TYPE_SECRET, CONCEALED_SECRET_MASK, CRED_FIELD_DATA, EXTERNAL_CREDENTIAL_TYPE
from .sd_helper import get_app_name_sd, get_version, is_matching, is_duplicating, basic_merge_multiple, basic_merge, basic_exclusion_merge, MergeType, calculate_merge_mode, get_sd_dir, get_sd_dir_by_env_cluster_name, SD_FILE_NAME, DELTA_SD_FILE_NAME
from .yaml_validator import checkByWhiteList, checkByBlackList, checkSchemaValidationFailed, getSchemaValidationErrorMessage
from .constants import cleanup_targets
from .params_helper import validate_parameters
from .models import CaseInsensitiveEnum, TemplateVersionUpdateMode, SbomRetentionConfig, OperationType, BgdOperation, DeltaDeployType, PipelineType, SaveArtifactsStrategy, ExternalCredentialProvisioning, SecretStore, PropertyMapping, ExternalCredential, BaseModel, Field, Optional, Enum
from .current_env_instance_store import CurrentEnvInstanceStore, current_env_instance_store, open_current_env_instance_store
from .external_credential_helper import resolve_external_credential_reference, resolve_external_credential_data, extract_external_cred, is_external_credential_reference
from .logger import logger, CustomFormatter, log_section, colorize, banner, colorize_segment
from .errors import ValidationError
from envgene_shared.crypto import crypt
from envgene_shared.crypto.crypt import decrypt_file
