- version: "Test-App-Name:0.0.1-Test"
  deployPostfix: "app"
  namespace: "test-solution-structure-case-01-app"
  wave: 0
  generationType: "UniqForApp"
  generationId: ""
- version: "Test-App-DB-Name:0.0.1-Test"
  deployPostfix: "app-core"
  namespace: "test-solution-structure-case-01-app-core"
  wave: 0
  generationType: "UniqForApp"
  generationId: ""
- version: "Test-App-Name:0.0.2-Test"
  deployPostfix: "app"
  namespace: "test-solution-structure-case-01-app"
  wave: 0
  generationType: "UniqForApp"
  generationId: ""
