version: "2.5"
cloud:
  CLOUD_API_HOST: "https://custom-location-api.example.com"
  CLOUD_API_PORT: "6443"
  CLOUD_PRIVATE_HOST: "custom-location-internal.example.com"
  CLOUD_PUBLIC_HOST: "custom-location-public.example.com"
  CLOUD_DASHBOARD_URL: "https://custom-location-dashboard.example.com"
  CLOUD_DEPLOY_TOKEN: "custom-location-deploy-token"
  CLOUD_PROTOCOL: "https"
  PRODUCTION_MODE: "false"
storage:
  STORAGE_ADDRESS: "storage-custom.example.com:9000"
