#!/bin/sh
set -e

YELLOW='\033[1;33m'
NC='\033[0m' # No Color

VENV_NAME=".git_hook_venv"
change_file=0

REPO_ROOT="$(git rev-parse --show-toplevel)"

activate_venv() {
  BIN_DIR_NAME=$1
  VENV_PATH="$REPO_ROOT/$VENV_NAME/$BIN_DIR_NAME/activate"

  if [ -f $VENV_PATH ]; then
    echo "Using $VENV_PATH"
    . $VENV_PATH
  else
    echo "Virtual environment $VENV_NAME not found. Running hook without it"
  fi
}

case "$(uname -s)" in
  CYGWIN*|MINGW*|MSYS*)
    PYTHONPATH_ROOT="$(cygpath -m "$REPO_ROOT")"
	JSON_SCHEMAS_DIR="$(cygpath -m "$REPO_ROOT/git_hooks/envgene_shared/schemas")"
    activate_venv "Scripts"
    ;;
  *)
    PYTHONPATH_ROOT="$REPO_ROOT"
	JSON_SCHEMAS_DIR="$REPO_ROOT/git_hooks/envgene_shared/schemas"
    activate_venv "bin"
    ;;
esac


if [ -z "$SECRET_KEY" ] && [ -s "$REPO_ROOT/.git/secret_key.txt" ]; then
    export SECRET_KEY="$(cat "$REPO_ROOT/.git/secret_key.txt")"
fi
if [ -z "$PUBLIC_AGE_KEYS" ] && [ -s "$REPO_ROOT/.git/age_public_key.txt" ]; then
    export PUBLIC_AGE_KEYS="$(cat "$REPO_ROOT/.git/age_public_key.txt")"
fi
if [ -z "$ENVGENE_AGE_PRIVATE_KEY" ] && [ -s "$REPO_ROOT/.git/private-age-key.txt" ]; then
    export ENVGENE_AGE_PRIVATE_KEY="$(cat "$REPO_ROOT/.git/private-age-key.txt")"
fi


export JSON_SCHEMAS_DIR="$REPO_ROOT/git_hooks/envgene_shared/schemas"
export PYTHONPATH="$PYTHONPATH_ROOT/git_hooks"


python -m envgene_shared.crypt_cli encrypt_all

# --- Git add if changes were made ---
echo "✅ Create a new commit with encrypted cred files"
git add ./*
