name: dummy-passport
cloudInfo:
  endpoints:
    apiEndpoint:
      url: "API.cl-01.managed.qubership.cloud"
      port: 443
      protocol: "https"
    publicEndpoint:
      url: "apps.cl-01.managed.qubership.cloud"
      protocol: "https"

