---
openapi: 3.1.0
info:
  title: operational-service API
  version: 2.0.0
paths:
  /colly/operational-service/v2/auth-status:
    get:
      responses:
        "200":
          description: OK
          headers:
            X-API-Version:
              schema:
                type: string
      summary: Get Auth Status
      tags:
      - Cluster Resources Rest
  /colly/operational-service/v2/clusters:
    get:
      responses:
        "200":
          description: OK
          headers:
            X-API-Version:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ClusterDTO"
      summary: Get Clusters
      tags:
      - Cluster Resources Rest
  /colly/operational-service/v2/clusters/{clusterName}:
    post:
      parameters:
      - name: clusterName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                description:
                  type: string
        required: true
      responses:
        "201":
          description: Created
          headers:
            X-API-Version:
              schema:
                type: string
        "401":
          description: Not Authorized
          headers:
            X-API-Version:
              schema:
                type: string
        "403":
          description: Not Allowed
          headers:
            X-API-Version:
              schema:
                type: string
      summary: Save Cluster
      tags:
      - Cluster Resources Rest
      security:
      - SecurityScheme:
        - admin
  /colly/operational-service/v2/environments:
    get:
      responses:
        "200":
          description: OK
          headers:
            X-API-Version:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EnvironmentDTO"
      summary: Get Environments
      tags:
      - Cluster Resources Rest
  /colly/operational-service/v2/environments/{envId}:
    post:
      parameters:
      - name: envId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                owner:
                  type: string
                description:
                  type: string
                status:
                  type: string
                labels:
                  type: array
                  items:
                    type: string
                type:
                  type: string
                team:
                  type: string
                deploymentStatus:
                  type: string
                ticketLinks:
                  type: string
                expirationDate:
                  type: string
        required: true
      responses:
        "201":
          description: Created
          headers:
            X-API-Version:
              schema:
                type: string
        "401":
          description: Not Authorized
          headers:
            X-API-Version:
              schema:
                type: string
        "403":
          description: Not Allowed
          headers:
            X-API-Version:
              schema:
                type: string
      summary: Save Environment
      tags:
      - Cluster Resources Rest
      security:
      - SecurityScheme:
        - admin
    delete:
      parameters:
      - name: envId
        in: path
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
          headers:
            X-API-Version:
              schema:
                type: string
        "401":
          description: Not Authorized
          headers:
            X-API-Version:
              schema:
                type: string
        "403":
          description: Not Allowed
          headers:
            X-API-Version:
              schema:
                type: string
      summary: Delete Environment
      tags:
      - Cluster Resources Rest
      security:
      - SecurityScheme:
        - admin
  /colly/operational-service/v2/metadata:
    get:
      responses:
        "200":
          description: OK
          headers:
            X-API-Version:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationMetadata"
      summary: Get Metadata
      tags:
      - Cluster Resources Rest
  /colly/operational-service/v2/tick:
    post:
      responses:
        "201":
          description: Created
          headers:
            X-API-Version:
              schema:
                type: string
      summary: Load Environments Manually
      tags:
      - Cluster Resources Rest
components:
  schemas:
    ApplicationMetadata:
      type: object
      properties:
        monitoringColumns:
          type: array
          items:
            type: string
        syncInterval:
          description: "synchronization period with cluster in human-readable duration notation"
          # чекнуть дататип
          type: string
    ClusterDTO:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        syncStatus:
          type: boolean
          properties:
            lastSyncResult: 
              type: boolean
            lastSyncCompletedAt:
              $ref: "#/components/schemas/Instant"
            lastSyncAttemptAt: # чекнуть
              $ref: "#/components/schemas/Instant"
    DeploymentStatus:
      type: string
      enum:
      - DEPLOYED
      - FAILED
      - IN_PROGRESS
      - NOT_STARTED
    EnvironmentDTO:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        namespaces:
          type: array
          items:
            $ref: "#/components/schemas/NamespaceDTO"
        cluster:
          $ref: "#/components/schemas/ClusterDTO"
        owner:
          type: string
        team:
          type: string
        status:
          $ref: "#/components/schemas/EnvironmentStatus"
        expirationDate:
          $ref: "#/components/schemas/LocalDate"
        type:
          $ref: "#/components/schemas/EnvironmentType"
        labels:
          type: array
          items:
            type: string
        description:
          type: string
        cleanInstallationDate:
          $ref: "#/components/schemas/Instant"
        monitoringData:
          type: object
          additionalProperties:
            type: string
        deploymentStatus:
          $ref: "#/components/schemas/DeploymentStatus"
        ticketLinks:
          type: string
        # Supported query parameters for filtering deployment operations history:
        # - sort: string (default: "-startedAt") - sort order ("startedAt" for ascending, "-startedAt" for descending)
        # - result: DeploymentOperationResult enum - filters by operation result
        # - mode: DeploymentOperationMode enum - filters by deployment mode
        # дорого
        # это таргет когда сделаем не знаем, возможно будт шорт терм аля cleanInstallationDate
        deploymentOperationsHistory:
          type: array
          description: "Contains deployment operations from all namespaces (5 most recent for each deployment) that are part of the environment. Operations with CLEAN_INSTALL mode remove all previous ones"
          items:
            $ref: "#/components/schemas/DeploymentOperationExecutionDTO"
        # ex-deploymentVersion
        installedSolutionDescriptors:
          type: array
          description: "List of Solution Descriptors installed in the environment's namespaces"
          items:
            $ref: "#/components/schemas/SolutionDescriptorRef"
    # Users cannot add statuses on their own. Users can create labels and assign them to environments
    EnvironmentStatus:
      type: string
      enum:
      - IN_USE
      - RESERVED
      - FREE
      - MIGRATING
      - TO_BE_DEPRECATED
    # Users can add types on their own via UI.
    EnvironmentType:
      type: string
      enum:
      - DEV
      - QA
      - PROJECT_CI
      - SAAS
      - JOINT_CI
      - OTHER
    Instant:
      type: string
      format: date-time
      examples:
      - 2022-03-10T16:15:50Z
    LocalDate:
      type: string
      format: date
      examples:
      - 2022-03-10
    NamespaceDTO:
      type: object
      properties:
        uid:
          type: string
        name:
          type: string
        existsInK8s:
          type: boolean
        deployPostfix:
          type: string
          description: "Deploy postfix, namespace role in solution"
    # TODO find out what other statuses exist, if there are only two, it might be possible to refactor to boolean
    DeploymentOperationResult:
      type: string
      description: "Deployment operation result"
      enum:
      - SUCCESS
      - FAIL
    DeploymentOperationMode:
      type: string
      description: "Deployment operation mode. ROLLING_UPDATE installs applications on top of existing ones. CLEAN_INSTALL removes all objects in the namespace before installation"
      enum:
      - ROLLING_UPDATE
      - CLEAN_INSTALL
    DeploymentOperationExecutionDTO:
      type: object
      description: "Deployment operation execution"
      properties:
        id:
          type: string
        startedAt:
          $ref: "#/components/schemas/Instant"
        operations:
          type: array
          items:
            $ref: "#/components/schemas/SolutionDescriptorDeploymentOperationDTO"
    SolutionDescriptorDeploymentOperationDTO:
      type: object
      description: "Operation for deploying applications described in the Solution Descriptor"
      properties:
        id:
          type: string
        result:
          $ref: "#/components/schemas/DeploymentOperationResult"
        mode:
          $ref: "#/components/schemas/DeploymentOperationMode"
        solutionDescriptor:
          type: string
  securitySchemes:
    SecurityScheme:
      type: openIdConnect
      description: Authentication
      openIdConnectUrl: http://host.docker.internal:8180/realms/quarkus/.well-known/openid-configuration