/*
 * Copyright 2024-2025 NetCracker Technology Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
package org.qubership.cloud.devops.cli;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import org.junit.jupiter.api.Test;

import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

public class EffectiveSetTest {

    private final ObjectMapper yamlMapper = new ObjectMapper(new YAMLFactory());

    @Test
    void testYamlGenerationAndComparison() throws Exception {

        // --------------------------------------------
        // 1. Load expected YAML from test resources
        // --------------------------------------------
        InputStream expectedYamlStream =
                getClass().getClassLoader()
                        .getResourceAsStream("expected-deployment.yaml");

        assertNotNull(expectedYamlStream, "Expected YAML file not found in test resources!");
        JsonNode expectedYaml = yamlMapper.readTree(expectedYamlStream);


        // --------------------------------------------
        // 2. Create TEMP directory for generated output
        // --------------------------------------------
        Path tempOutputDir = Files.createTempDirectory("effective-set-output");

        // Simulate code that generates YAML file
        // For example, your parser.writeToFile() would produce this file.
        Path generatedFile = tempOutputDir.resolve("deployment.yaml");

        String generatedYamlContent = """
                key1: value1
                key2:
                  nested: 123
                array:
                  - a
                  - b
                """;

        Files.writeString(generatedFile, generatedYamlContent);


        // --------------------------------------------
        // 3. Read actual YAML generated by your code
        // --------------------------------------------
        assertTrue(Files.exists(generatedFile), "Generated YAML file not found!");

        JsonNode actualYaml =
                yamlMapper.readTree(Files.newInputStream(generatedFile));


        // --------------------------------------------
        // 4. Structural YAML comparison (order independent)
        // --------------------------------------------
        assertEquals(expectedYaml,
                     actualYaml,
                     "Generated YAML does not match expected YAML!");

        System.out.println("✔ YAML comparison passed successfully.");
    }
}
*/
