name: Lint Code Base

inputs:
  full_scan:
    description: "Lint all codebase"
    required: false
    default: 'false'
  github-token:
    description: "GitHub token"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: "Load super-linter environment file"
      shell: bash
      run: |
        # shellcheck disable=2086
        if [ -f "./.github/super-linter.env" ]; then
          grep "\S" ./.github/super-linter.env | grep -v "^#"
          grep "\S" ./.github/super-linter.env | grep -v "^#" >> $GITHUB_ENV
        fi

    - name: Lint Code Base
      uses: super-linter/super-linter@v7.4.0
      env:
        VALIDATE_ALL_CODEBASE: ${{ inputs.full_scan == 'true' }}
        GITHUB_TOKEN: ${{ inputs.github-token }}