name: Lint Code Base
description: 'Run Code Base Linters'

inputs:
  full_scan:
    description: "Lint all codebase"
    required: false
    default: 'false'
  github-token:
    description: "GitHub token"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: "Load super-linter environment file"
      shell: bash
      run: |
        # shellcheck disable=2086
        if [ -f "./.github/super-linter.env" ]; then
          grep "\S" ./.github/super-linter.env | grep -v "^#"
          grep "\S" ./.github/super-linter.env | grep -v "^#" >> $GITHUB_ENV
        fi

    - name: Predefine GIT_BEFORE_SHA_HEAD for workflow_dispatch
      if: ${{ github.event_name == 'workflow_dispatch' }}
      shell: bash
      run: |
        # Align with Super-Linter's expected rev-parse input
        BEFORE_REF="${DEFAULT_BRANCH:-origin/main}"
        echo "GIT_BEFORE_SHA_HEAD=${BEFORE_REF}" >> "$GITHUB_ENV"

    - name: Lint Code Base
      uses: super-linter/super-linter@v8.2.0
      env:
        VALIDATE_ALL_CODEBASE: ${{ inputs.full_scan == 'true' || github.event_name == 'workflow_dispatch' }}
        GITHUB_TOKEN: ${{ inputs.github-token }}