cred-1:
  type: usernamePassword
  data:
    username: u1
    password: p1_new
cred-2:
  type: usernamePassword
  data:
    username: p2_new
    password: p2
cred-3:
  type: secret
  data:
    secret: s3_new
