- wave: 0
  version: app-core:1.0.0
  deployPostfix: dev-1-core
  namespace: dev-1-core
- wave: 0
  version: app-bss-origin:1.0.0
  deployPostfix: dev-1-bss-origin
  namespace: dev-1-bss-origin
- wave: 0
  version: app-bss-peer:1.0.0
  deployPostfix: dev-1-bss-peer
  namespace: dev-1-bss-peer
- wave: 0
  version: app-controller:1.0.0
  deployPostfix: dev-1-controller
  namespace: dev-1-controller
- wave: 0
  version: app-oss:1.0.0
  deployPostfix: dev-1-oss
  namespace: dev-1-oss
