
service-activator-integration-cred: # shared credentials: prod-integration-creds
  type: usernamePassword
  data:
    username: "test_username"
    password: "test_password"
tibco-integration-cred: # shared credentials: prod-integration-creds
  type: usernamePassword
  data:
    username: "test_username"
    password: "test_password"