name: "Tests: Qubership Envgene tests"

run-name: "Smoke tests on commit ${{ github.sha }}"

on:
  workflow_dispatch: {}
  workflow_call: {}
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

env:
  CI_PROJECT_DIR: ${{ github.workspace }}

jobs:
  linters:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' || github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref != 'refs/heads/main' && !startsWith(github.event.head_commit.message, 'fix:') && !startsWith(github.event.head_commit.message, 'feat:') && !startsWith(github.event.head_commit.message, 'breaking change') && !startsWith(github.event.head_commit.message, 'BREAKING CHANGE')) }}
    steps:
      - name: Run linters checks
        uses: ./.github/workflows/super-linter.yaml
  
  pytest:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' || github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref != 'refs/heads/main' && !startsWith(github.event.head_commit.message, 'fix:') && !startsWith(github.event.head_commit.message, 'feat:') && !startsWith(github.event.head_commit.message, 'breaking change') && !startsWith(github.event.head_commit.message, 'BREAKING CHANGE')) }}
    container:
      image: python:3.12-slim-bookworm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0

      - name: Run Tests
        uses: ./.github/actions/run-tests
