name: "Tests"

on:
  pull_request:
    branches:
      - '**'

env:
  CI_PROJECT_DIR: ${{ github.workspace }}

jobs:
  tests:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'workflow_call' ||
      (github.event_name == 'pull_request') ||
      (github.event_name == 'push' && 
       github.ref != 'refs/heads/main' &&
       !contains(github.event.head_commit.message, 'fix') && 
       !contains(github.event.head_commit.message, 'feat') && 
       !contains(github.event.head_commit.message, 'breaking change'))
    container:
      image: python:3.12-slim-bookworm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Tests
        uses: ./.github/actions/run-tests
