name: "Tests: Qubership Envgene tests"

run-name: "Smoke tests on commit ${{ github.sha }}"

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

env:
  CI_PROJECT_DIR: ${{ github.workspace }}

jobs:
  conventional-commits:
    uses: ./.github/workflows/pr-conventional-commits.yaml

  pytest:
    needs: [conventional-commits]
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'workflow_call' ||
      (github.event_name == 'pull_request') ||
      (github.event_name == 'push' && 
       github.ref != 'refs/heads/main' &&
       !contains(github.event.head_commit.message, 'fix') && 
       !contains(github.event.head_commit.message, 'feat') && 
       !contains(github.event.head_commit.message, 'breaking change'))
    container:
      image: python:3.10-slim-bookworm
    steps:
      - name: Run Tests
        uses: ./.github/actions/run-tests  